"""Generate the paper's LaTeX result tables STRAIGHT from the result files, so no number
is hand-transcribed. Reads the C1 output CSVs + the two falsification .txt files and writes
05_paper/drafts/tables/c1_tables.tex (booktabs). Re-run any time results change.
"""
import re
from pathlib import Path
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
H1 = ROOT / "04_empirics" / "H1_volatility" / "output"
V0 = ROOT / "04_empirics" / "V0_lost_results_replication" / "output"
OUT = ROOT / "05_paper" / "drafts" / "tables"
OUT.mkdir(parents=True, exist_ok=True)

rob = pd.read_csv(H1 / "c1_robustness.csv")
sdid = pd.read_csv(H1 / "c1_sdid_results.csv")
scm = pd.read_csv(H1 / "c1_scm_results.csv")
dscm = pd.read_csv(H1 / "c1_scm_district_results.csv")
placebo_txt = (V0 / "placebo_results.txt").read_text()
boot_txt = (V0 / "wild_bootstrap_results.txt").read_text()


def grab(pat, txt, g=1, cast=float):
    m = re.search(pat, txt, re.DOTALL)
    return cast(m.group(g)) if m else None


# --- numbers parsed from the falsification text files ---
did_base = rob[rob.spec.str.contains("baseline")].iloc[0]
did_pct, did_p = did_base.effect_pct, did_base.p_default
# honest few-cluster p (CR1 t on G-1 df); the naive `p` column is over-optimistic.
did_p_cr1 = did_base["p_cr1_t(G-1)"]
did_nobs, did_nunits = int(did_base.nobs), int(did_base.n_units)
boot_main = grab(r"MAIN DiD.*?bootstrap p .*?=\s*([0-9.]+)", boot_txt, 1)
plac_pct = grab(r"PLACEBO .*?\(([-0-9.]+)%\)", placebo_txt, 1)
plac_p = grab(r"PLACEBO .*?p=([0-9.]+)", placebo_txt, 1)
boot_plac = grab(r"PLACEBO.*?bootstrap p .*?=\s*([0-9.]+)", boot_txt, 1)
lead_stat = grab(r"JOINT LEAD TEST.*?stat=([0-9.]+)", placebo_txt, 1)
lead_p = grab(r"JOINT LEAD TEST.*?p=([0-9.]+)", placebo_txt, 1)

pooled = sdid[sdid.spec == "pooled"].iloc[0]

L = []
W = L.append

# ---------------- Table 1: convergent main estimates ----------------
W(r"% Auto-generated by 00_code/make_paper_tables.py — do not hand-edit.")
W(r"\begin{table}[t]\centering")
W(r"\caption{The volatility effect of the suspension: current food-donor rerun (district-median $\ln$ rv30, paddy dropped).}")
W(r"\label{tab:c1main}")
W(r"\begin{tabular}{lcc}\toprule")
W(r"Estimator & Effect on spot volatility & Inference \\ \midrule")
W(rf"Two-way-FE DiD & ${did_pct:.1f}\%$ & CR1 $p={did_p_cr1:.3f}$; ${boot_main:.3f}$ wild boot (not significant) \\")
W(rf"Synthetic DiD (pooled) & ${pooled.att_pct:.1f}\%$ & placebo SE; $z={pooled.z:.2f}$ (borderline) \\")
scm_clean = scm[~scm.msp_flag]
W(rf"Synthetic control (commodity) & chana ${scm.set_index('commodity').loc['chana','att_pct']:.1f}\%$ & chana at placebo floor $p={scm.set_index('commodity').loc['chana','placebo_p']:.3f}$ \\")
W(rf"District-unit synthetic control & median ${dscm.median_att_pct.median():.0f}\%$ & placebo floor $p=1/10$ with 9 donors \\")
W(r"\bottomrule\end{tabular}")
W(rf"\par\smallskip\footnotesize The inherited $+8$--$10\%$ claim is refuted, but the current aggregate DiD is only ${did_pct:.1f}\%$ (estimated on {did_nobs:,} obs / {did_nunits:,} units) and is not significant under honest few-cluster inference. The substantive result is donor sensitivity: lower-volatility evidence is concentrated in chana, while the aggregate effect halves relative to the clean-core $-20.7\%$ run once food-cereal donors enter. Treatment is staggered per commodity; inference is clustered by commodity.")
W(r"\end{table}")
W("")

# ---------------- Table 2: per-commodity ----------------
W(r"\begin{table}[t]\centering")
W(r"\caption{Per-commodity volatility effects: Synthetic DiD and synthetic control.}")
W(r"\label{tab:c1percommodity}")
W(r"\begin{tabular}{lccc}\toprule")
W(r"Commodity & SDID ATT (\%) & placebo $z$ & SCM ATT (\%) \\ \midrule")
sd = sdid[sdid.spec == "per_commodity"].set_index("commodity")
sc = scm.set_index("commodity")
for c in ["chana", "mustard", "wheat", "soybean", "moong"]:
    if c in sd.index and c in sc.index:
        flag = r"$^{\dagger}$" if bool(sc.loc[c, "msp_flag"]) else ""
        W(rf"{c}{flag} & ${sd.loc[c,'att_pct']:.1f}$ & ${sd.loc[c,'z']:.1f}$ & ${sc.loc[c,'att_pct']:.1f}$ \\")
W(r"\bottomrule\end{tabular}")
W(r"\par\smallskip\footnotesize $^{\dagger}$ wheat is MSP-flagged (price partly support-administered). paddy is dropped (MSP-censored). Chana is the strongest and cleanest lower-volatility case; wheat collapses to approximately zero under SDID, consistent with MSP/export-ban confounding.")
W(r"\end{table}")
W("")

# ---------------- Table 3: falsification ----------------
W(r"\begin{table}[t]\centering")
W(r"\caption{Falsification battery (current food-donor rerun).}")
W(r"\label{tab:falsification}")
W(r"\begin{tabular}{lcc}\toprule")
W(r"Test & Statistic & Verdict \\ \midrule")
W(rf"Main DiD (real ban) & ${did_pct:.1f}\%$, CR1 $p={did_p_cr1:.3f}$ / boot ${boot_main:.3f}$ & not significant \\")
W(rf"Placebo (fake 2019 ban) & ${plac_pct:.1f}\%$, $p={plac_p:.3f}$ / boot ${boot_plac:.3f}$ & cleanly insignificant \\")
W(rf"Joint pre-trend lead test & stat $={lead_stat:.2f}$, $p={lead_p:.3f}$ & not rejected jointly \\")
W(r"\bottomrule\end{tabular}")
W(r"\par\smallskip\footnotesize The food-donor rerun improves falsification: the placebo is smaller and insignificant, and the joint lead test does not reject. The main aggregate effect also becomes insignificant, so the honest reading is a chana-centered donor-sensitivity result rather than a robust aggregate effect.")
W(r"\end{table}")
W("")

# ---------------- Table 4: robustness ----------------
W(r"\begin{table}[t]\centering")
W(r"\caption{Robustness of the aggregate DiD: district-liquidity / outlier filters and leave-one-commodity-out.}")
W(r"\label{tab:robustness}")
W(r"\begin{tabular}{lccc}\toprule")
W(r"Specification & Effect (\%) & few-cluster $p$ & $N$ obs \\ \midrule")
filt = rob[~rob.spec.str.startswith("ex-")]
loo = rob[rob.spec.str.startswith("ex-")]
for _, r in filt.iterrows():
    name = r.spec.replace("@", r"\,@\,").replace("%", r"\%").replace(">", r"$>$")
    W(rf"{name} & ${r.effect_pct:.1f}$ & ${r['p_cr1_t(G-1)']:.3f}$ & {int(r.nobs):,} \\")
if len(loo):
    W(r"\midrule \multicolumn{4}{l}{\emph{Leave-one-commodity-out (drop each treated unit)}} \\")
    for _, r in loo.iterrows():
        name = r.spec.replace("ex-", "ex-")
        W(rf"{name} & ${r.effect_pct:.1f}$ & ${r['p_cr1_t(G-1)']:.3f}$ & {int(r.nobs):,} \\")
W(r"\bottomrule\end{tabular}")
W(r"\par\smallskip\footnotesize Honest few-cluster $p$ (CR1 $t$, $G{-}1$ df). The aggregate effect remains negative but insignificant across filters. Dropping wheat gives a significant negative estimate, while dropping chana weakens the result; this reinforces the current reading that the lower-volatility signal is concentrated in chana and that wheat is confounded.")
W(r"\end{table}")

(OUT / "c1_tables.tex").write_text("\n".join(L) + "\n")
print(f"wrote {OUT/'c1_tables.tex'}")
print(f"  DiD {did_pct:.1f}% (analytic p {did_p:.3f}, CR1 p {did_p_cr1:.3f}, boot {boot_main:.3f}) | SDID pooled {pooled.att_pct:.1f}% (z {pooled.z:.2f})")
print(f"  placebo {plac_pct:.1f}% p {plac_p:.3f}/boot {boot_plac:.3f} | pre-trend stat {lead_stat:.2f} p {lead_p:.3f}")
