"""Generate H1 LaTeX result tables directly from final result files.

Final H1 empirical structure:
  1. Two-way fixed-effects Difference-in-Differences
  2. Commodity-level Synthetic Control
  3. District-unit Synthetic Control as heterogeneity analysis
  4. Placebo, pre-trend, robustness, and leave-one-out diagnostics

Inference for the aggregate DiD is clustered by commodity. Because the
number of commodity clusters is small, the clustered t statistic is also
evaluated against a t(G-1) reference distribution.

No table values are hand-transcribed.
"""

import re
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]

H1 = (
    ROOT /
    "04_empirics" /
    "H1_volatility" /
    "output"
)

V0 = (
    ROOT /
    "04_empirics" /
    "V0_lost_results_replication" /
    "output"
)

OUT = (
    ROOT /
    "05_paper" /
    "drafts" /
    "tables"
)

OUT.mkdir(parents=True, exist_ok=True)


rob = pd.read_csv(
    H1 / "c1_robustness.csv"
)

scm = pd.read_csv(
    H1 / "c1_scm_results.csv"
)

dscm = pd.read_csv(
    H1 / "c1_scm_district_results.csv"
)

placebo_txt = (
    V0 /
    "placebo_results.txt"
).read_text()


def grab(pattern, text, group=1, cast=float):
    m = re.search(
        pattern,
        text,
        re.DOTALL
    )

    return (
        cast(m.group(group))
        if m else None
    )


# ---------------------------------------------------------
# Main DiD
# ---------------------------------------------------------

did_base = (
    rob[
        rob.spec.str.contains(
            "baseline"
        )
    ]
    .iloc[0]
)

did_pct = did_base.effect_pct
did_p = did_base.p_default

did_p_t = did_base[
    "p_t_Gminus1"
]

did_nobs = int(
    did_base.nobs
)

did_nunits = int(
    did_base.n_units
)


# ---------------------------------------------------------
# Falsification results
# ---------------------------------------------------------

plac_pct = grab(
    r"PLACEBO .*?\(([-0-9.]+)%\)",
    placebo_txt
)

plac_p = grab(
    r"PLACEBO .*?p=([0-9.]+)",
    placebo_txt
)

lead_stat = grab(
    r"JOINT LEAD TEST.*?stat=([0-9.]+)",
    placebo_txt
)

lead_f = grab(
    r"JOINT LEAD TEST.*?F_ref=([0-9.]+)",
    placebo_txt
)

lead_df_match = re.search(
    r"JOINT LEAD TEST.*?p_F\((\d+),(\d+)\)=([0-9.]+)",
    placebo_txt,
    re.DOTALL,
)

if lead_df_match is None:
    raise ValueError(
        "Could not parse small-cluster pre-trend F-reference result."
    )

lead_df1 = int(lead_df_match.group(1))
lead_df2 = int(lead_df_match.group(2))
lead_p_f = float(lead_df_match.group(3))


# ---------------------------------------------------------
# Build LaTeX
# ---------------------------------------------------------

L = []
W = L.append

W(
    r"% Auto-generated by "
    r"00_code/make_paper_tables.py — "
    r"do not hand-edit."
)


# =========================================================
# TABLE 1: MAIN METHODS
# =========================================================

W(r"\begin{table}[t]\centering")

W(
    r"\caption{Volatility effects of the suspension: "
    r"Difference-in-Differences and Synthetic Control.}"
)

W(r"\label{tab:c1main}")

W(
    r"\begin{tabular}{lcc}\toprule"
)

W(
    r"Estimator & Effect on spot volatility & Inference \\ \midrule"
)

W(
    rf"Two-way-FE DiD & "
    rf"${did_pct:.1f}\%$ & "
    rf"$t(G-1)$ reference $p={did_p_t:.3f}$ "
    rf"(not significant) \\"
)

sc = scm.set_index("commodity")

if "chana" in sc.index:
    W(
        rf"Synthetic Control: chana & "
        rf"${sc.loc['chana','att_pct']:.1f}\%$ & "
        rf"in-space placebo "
        rf"$p={sc.loc['chana','placebo_p']:.3f}$ \\"
    )

W(
    rf"District-unit Synthetic Control & "
    rf"median ${dscm.median_att_pct.median():.0f}\%$ & "
    rf"heterogeneity analysis \\"
)

W(r"\bottomrule\end{tabular}")

W(
    rf"\par\smallskip\footnotesize "
    rf"The aggregate DiD uses {did_nobs:,} observations "
    rf"across {did_nunits:,} commodity-district units. "
    rf"Inference is clustered by commodity. "
    rf"The aggregate estimate is negative but statistically "
    rf"insignificant; commodity-level Synthetic Control is "
    rf"used as the complementary counterfactual analysis."
)

W(r"\end{table}")

W("")


# =========================================================
# TABLE 2: SCM BY COMMODITY
# =========================================================

W(r"\begin{table}[t]\centering")

W(
    r"\caption{Commodity-level Synthetic Control estimates.}"
)

W(r"\label{tab:c1percommodity}")

W(
    r"\begin{tabular}{lcc}\toprule"
)

W(
    r"Commodity & SCM ATT (\%) & in-space placebo $p$ \\ \midrule"
)

for c in [
    "chana",
    "mustard",
    "wheat",
    "soybean",
    "moong",
]:
    if c not in sc.index:
        continue

    flag = (
        r"$^{\dagger}$"
        if str(
            sc.loc[c, "msp_flag"]
        ).lower() == "true"
        else ""
    )

    W(
        rf"{c}{flag} & "
        rf"${sc.loc[c,'att_pct']:.1f}$ & "
        rf"${sc.loc[c,'placebo_p']:.3f}$ \\"
    )

W(r"\bottomrule\end{tabular}")

W(
    r"\par\smallskip\footnotesize "
    r"$^{\dagger}$ Wheat is policy-confounded and is interpreted "
    r"cautiously. Paddy is excluded because of MSP-related price "
    r"censoring. Chana provides the strongest commodity-level "
    r"lower-volatility signal."
)

W(r"\end{table}")

W("")


# =========================================================
# TABLE 3: FALSIFICATION
# =========================================================

W(r"\begin{table}[t]\centering")

W(
    r"\caption{Falsification diagnostics for the preferred DiD.}"
)

W(r"\label{tab:falsification}")

W(
    r"\begin{tabular}{lcc}\toprule"
)

W(
    r"Test & Statistic & Verdict \\ \midrule"
)

W(
    rf"Main DiD & "
    rf"${did_pct:.1f}\%$, "
    rf"$t(G-1)$ $p={did_p_t:.3f}$ & "
    rf"not significant \\"
)

W(
    rf"Fake December-2019 treatment & "
    rf"${plac_pct:.1f}\%$, "
    rf"$p={plac_p:.3f}$ & "
    rf"insignificant \\"
)

lead_interpretation = (
    "rejected jointly"
    if lead_p_f < 0.05
    else "not rejected jointly"
)

W(
    rf"Joint pre-treatment lead test & "
    rf"$F({lead_df1},{lead_df2})={lead_f:.2f}$, "
    rf"$p={lead_p_f:.4f}$ & "
    rf"{lead_interpretation} \\"
)

W(r"\bottomrule\end{tabular}")

W(r"\end{table}")

W("")


# =========================================================
# TABLE 4: ROBUSTNESS
# =========================================================

W(r"\begin{table}[t]\centering")

W(
    r"\caption{Robustness and leave-one-treated-commodity-out "
    r"analysis for the aggregate DiD.}"
)

W(r"\label{tab:robustness}")

W(
    r"\begin{tabular}{lccc}\toprule"
)

W(
    r"Specification & Effect (\%) & "
    r"$t(G-1)$ $p$ & $N$ \\ \midrule"
)

filters = rob[
    ~rob.spec.str.startswith("ex-")
]

loo = rob[
    rob.spec.str.startswith("ex-")
]

for _, r in filters.iterrows():
    name = (
        r.spec
        .replace("@", r"\,@\,")
        .replace("%", r"\%")
        .replace(">", r"$>$")
    )

    W(
        rf"{name} & "
        rf"${r.effect_pct:.1f}$ & "
        rf"${r['p_t_Gminus1']:.3f}$ & "
        rf"{int(r.nobs):,} \\"
    )

if len(loo):
    W(
        r"\midrule "
        r"\multicolumn{4}{l}{"
        r"\emph{Leave-one-treated-commodity-out}} \\"
    )

    for _, r in loo.iterrows():
        W(
            rf"{r.spec} & "
            rf"${r.effect_pct:.1f}$ & "
            rf"${r['p_t_Gminus1']:.3f}$ & "
            rf"{int(r.nobs):,} \\"
        )

W(r"\bottomrule\end{tabular}")

W(
    r"\par\smallskip\footnotesize "
    r"The aggregate sign remains negative across the main "
    r"sample-quality filters. Dropping wheat strengthens the "
    r"negative estimate, while dropping chana weakens it."
)

W(r"\end{table}")


out = (
    OUT /
    "c1_tables.tex"
)

out.write_text(
    "\n".join(L) + "\n"
)

print("wrote", out)

print(
    f"DiD: {did_pct:.1f}% | "
    f"clustered p={did_p:.4f} | "
    f"t(G-1) p={did_p_t:.4f}"
)

print(
    f"Placebo: {plac_pct:.1f}% | "
    f"p={plac_p:.4f}"
)

print(
    f"Pre-trend joint "
    f"F({lead_df1},{lead_df2})={lead_f:.2f} | "
    f"p={lead_p_f:.4f}"
)
